"use client";

import { useQuery, useMutation, UseQueryOptions, UseMutationOptions, QueryKey } from "@tanstack/react-query";
import * as z from "zod";

// Types from the OpenAPI spec generated by Orval
const HealthCheckResponse = z.object({
  status: z.string(),
});

const FetchCompetitorVideosBody = z.object({
  competitors: z.array(z.string()).min(1).max(3),
  youtubeApiKey: z.string().nullish(),
  limit: z.number().optional(),
});

const FetchCompetitorVideosResponse = z.object({
  videos: z.array(
    z.object({
      id: z.number(),
      competitor: z.string(),
      title: z.string(),
      views: z.string(),
      url: z.string(),
      publishedAt: z.string().nullish(),
      thumbnailUrl: z.string().nullish(),
    })
  ),
  usedMockData: z.boolean(),
});

const GetVideosQueryParams = z.object({
  competitor: z.coerce.string().optional(),
});

const AnalyzeTitlesBody = z.object({
  titles: z.array(z.string()),
  outputMode: z.enum(["docs", "text"]),
  customPrompt: z.string().nullish(),
});

const AnalyzeTitlesResponse = z.object({
  analysis: z.string(),
  id: z.number(),
  outputMode: z.enum(["docs", "text"]),
  createdAt: z.string(),
});

const GenerateTitlesBody = z.object({
  analysis: z.string(),
  niche: z.string().nullish(),
  outputMode: z.enum(["docs", "text"]),
  customGeneratePrompt: z.string().nullish(),
  libraryFormat: z.string().nullish(),
  limit: z.number().optional(),
});

const GenerateTitlesResponse = z.object({
  titles: z.array(z.string()),
  explanation: z.string(),
});

const AnalyzeScriptBody = z.object({
  script: z.string(),
  outputMode: z.enum(["docs", "text"]),
});

const AnalyzeScriptResponse = z.object({
  analysis: z.string(),
  id: z.number(),
  outputMode: z.enum(["docs", "text"]),
  createdAt: z.string(),
});

const GenerateScriptBody = z.object({
  title: z.string(),
  scriptAnalysis: z.string().nullish(),
  targetWordCountMode: z.string().optional(),
  targetWordCount: z.number().nullish(),
  outputMode: z.enum(["docs", "text"]),
});

const GenerateScriptResponse = z.object({
  id: z.number(),
  title: z.string(),
  script: z.string(),
  wordCount: z.number(),
  outputMode: z.enum(["docs", "text"]),
  createdAt: z.string(),
});

// Type definitions
export type HealthCheckResponse = z.infer<typeof HealthCheckResponse>;
export type FetchCompetitorVideosBody = z.infer<typeof FetchCompetitorVideosBody>;
export type FetchCompetitorVideosResponse = z.infer<typeof FetchCompetitorVideosResponse>;
export type GetVideosQueryParams = z.infer<typeof GetVideosQueryParams>;
export type AnalyzeTitlesBody = z.infer<typeof AnalyzeTitlesBody>;
export type AnalyzeTitlesResponse = z.infer<typeof AnalyzeTitlesResponse>;
export type GenerateTitlesBody = z.infer<typeof GenerateTitlesBody>;
export type GenerateTitlesResponse = z.infer<typeof GenerateTitlesResponse>;
export type AnalyzeScriptBody = z.infer<typeof AnalyzeScriptBody>;
export type AnalyzeScriptResponse = z.infer<typeof AnalyzeScriptResponse>;
export type GenerateScriptBody = z.infer<typeof GenerateScriptBody>;
export type GenerateScriptResponse = z.infer<typeof GenerateScriptResponse>;

export type TitleAnalysisHistory = AnalyzeTitlesResponse & { titles: string[] };
export type ScriptAnalysisHistory = AnalyzeScriptResponse & { scriptPreview: string };

export type DashboardStats = {
  totalVideos: number;
  totalCompetitors: number;
  totalTitleAnalyses: number;
  totalScriptAnalyses: number;
  totalGeneratedScripts: number;
  recentActivity: Array<{ type: string; label: string; createdAt: string }>;
};

// API Base URL
const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || "/api";

// Custom fetch function that matches the original API client
async function apiClient<T>(request: string, options?: RequestInit): Promise<T> {
  const response = await fetch(request, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(options?.headers || {}),
    },
    credentials: "same-origin",
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error || `HTTP ${response.status}: ${response.statusText}`);
  }

  const data = await response.json();
  return data as T;
}

// Custom hooks exports
export function useFetchCompetitorVideos(
  options: {
    mutation?: UseMutationOptions<FetchCompetitorVideosResponse, Error, { data: FetchCompetitorVideosBody }>;
  } = {}
) {
  const mutation = useMutation<FetchCompetitorVideosResponse, Error, { data: FetchCompetitorVideosBody }>({
    mutationFn: ({ data }) => apiClient<FetchCompetitorVideosResponse>(
      `${API_BASE_URL}/videos/fetch`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

export function useGetVideos(
  params?: GetVideosQueryParams,
  options?: Partial<UseQueryOptions<FetchCompetitorVideosResponse, Error>>
) {
  const queryKey = ["videos", params] as const;

  const query = useQuery<FetchCompetitorVideosResponse, Error>({
    queryKey,
    queryFn: () => apiClient<FetchCompetitorVideosResponse>(
      `${API_BASE_URL}/videos${params?.competitor ? `?competitor=${params.competitor}` : ""}`
    ),
    ...options,
  });

  return query;
}

export function useAnalyzeTitles(
  options: {
    mutation?: UseMutationOptions<AnalyzeTitlesResponse, Error, { data: AnalyzeTitlesBody }>;
  } = {}
) {
  const mutation = useMutation<AnalyzeTitlesResponse, Error, { data: AnalyzeTitlesBody }>({
    mutationFn: ({ data }) => apiClient<AnalyzeTitlesResponse>(
      `${API_BASE_URL}/titles/analyze`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

export function useGenerateTitles(
  options: {
    mutation?: UseMutationOptions<GenerateTitlesResponse, Error, { data: GenerateTitlesBody }>;
  } = {}
) {
  const mutation = useMutation<GenerateTitlesResponse, Error, { data: GenerateTitlesBody }>({
    mutationFn: ({ data }) => apiClient<GenerateTitlesResponse>(
      `${API_BASE_URL}/titles/generate`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

export function useAnalyzeScript(
  options: {
    mutation?: UseMutationOptions<AnalyzeScriptResponse, Error, { data: AnalyzeScriptBody }>;
  } = {}
) {
  const mutation = useMutation<AnalyzeScriptResponse, Error, { data: AnalyzeScriptBody }>({
    mutationFn: ({ data }) => apiClient<AnalyzeScriptResponse>(
      `${API_BASE_URL}/scripts/analyze`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

export function useGenerateScript(
  options: {
    mutation?: UseMutationOptions<GenerateScriptResponse, Error, { data: GenerateScriptBody }>;
  } = {}
) {
  const mutation = useMutation<GenerateScriptResponse, Error, { data: GenerateScriptBody }>({
    mutationFn: ({ data }) => apiClient<GenerateScriptResponse>(
      `${API_BASE_URL}/scripts/generate`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

import { SaveTitleFormatBody as SaveTitleFormatBodySchema } from "@/lib/validators";
export type SaveTitleFormatBody = z.infer<typeof SaveTitleFormatBodySchema>;

export function useSaveTitleFormat(
  options: {
    mutation?: UseMutationOptions<any, Error, { data: SaveTitleFormatBody }>;
  } = {}
) {
  const mutation = useMutation<any, Error, { data: SaveTitleFormatBody }>({
    mutationFn: ({ data }) => apiClient<any>(
      `${API_BASE_URL}/library/title-formats`, 
      { method: "POST", body: JSON.stringify(data) }
    ),
    ...options.mutation,
  });

  return mutation;
}

export type TitleFormat = {
  id: number;
  name: string;
  pattern: string;
  description: string | null;
  createdAt: string;
};

export function useGetTitleFormats(
  options?: Partial<UseQueryOptions<{ formats: TitleFormat[] }>>
) {
  const query = useQuery<{ formats: TitleFormat[] }, Error>({
    queryKey: ["title-formats"],
    queryFn: () => apiClient<{ formats: TitleFormat[] }>(`${API_BASE_URL}/library/title-formats`),
    ...options,
  });

  return query;
}

export function useGetTitleAnalyses(
  options?: Partial<UseQueryOptions<{ analyses: TitleAnalysisHistory[] }>>
) {
  const query = useQuery<{ analyses: TitleAnalysisHistory[] }, Error>({
    queryKey: ["title-analyses"],
    queryFn: () => apiClient<{ analyses: TitleAnalysisHistory[] }>(`${API_BASE_URL}/history/title-analyses`),
    ...options,
  });

  return query;
}

export function useGetScriptAnalyses(
  options?: Partial<UseQueryOptions<{ analyses: ScriptAnalysisHistory[] }>>
) {
  const query = useQuery<{ analyses: ScriptAnalysisHistory[] }, Error>({
    queryKey: ["script-analyses"],
    queryFn: () => apiClient<{ analyses: ScriptAnalysisHistory[] }>(`${API_BASE_URL}/history/script-analyses`),
    ...options,
  });

  return query;
}

export function useGetGeneratedScripts(
  options?: Partial<UseQueryOptions<{ scripts: GenerateScriptResponse[] }>>
) {
  const query = useQuery<{ scripts: GenerateScriptResponse[] }, Error>({
    queryKey: ["generated-scripts"],
    queryFn: () => apiClient<{ scripts: GenerateScriptResponse[] }>(`${API_BASE_URL}/history/generated-scripts`),
    ...options,
  });

  return query;
}

export function useGetDashboardStats(
  options?: Partial<UseQueryOptions<DashboardStats>>
) {
  const query = useQuery<DashboardStats, Error>({
    queryKey: ["dashboard-stats"],
    queryFn: () => apiClient<DashboardStats>(`${API_BASE_URL}/stats/dashboard`),
    ...options,
  });

  return query;
}

// Re-export query keys for invalidation
export const getGetVideosQueryKey = () => ["videos"] as const;
export const getGetTitleFormatsQueryKey = () => ["title-formats"] as const;
export const getGetTitleAnalysesQueryKey = () => ["title-analyses"] as const;
export const getGetScriptAnalysesQueryKey = () => ["script-analyses"] as const;
export const getGetGeneratedScriptsQueryKey = () => ["generated-scripts"] as const;
export const getGetDashboardStatsQueryKey = () => ["dashboard-stats"] as const;

